name: Deploy branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-checks:
    uses: ./.github/workflows/checks-subflow.yaml
  
  deploy-dev:
    needs: run-checks
    uses: ./.github/workflows/deploy-subflow.yaml
    secrets: inherit
    with:
      environment: Development

