name: Deploy subflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: The environment to deploy to (e.g., Development, Staging, Production).
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      RESOURCE_GROUP_NAME:
        required: true
        description: The name of the Azure resource group to deploy to.

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'function-app'       # set this to the path to your function app project, defaults to the repository root


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Bicep Deployment
        uses: azure/bicep-deploy@v2
        id: bicep-deploy
        with:
          type: deploymentStack
          operation: create
          name: Development
          location: eastus
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: resourceGroup
          resource-group-name: ${{ secrets.RESOURCE_GROUP_NAME }}
          template-file: ./bicep/main.bicep
          action-on-unmanage-resources: delete
          deny-settings-mode: none
      
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml' # Read python version from a file pyproject.toml
          cache: 'poetry' # caching poetry dependencies

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd '.'
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-plugin-export
          poetry export --without-hashes --with api --format=requirements.txt > function-app/requirements.txt
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ steps.bicep-deploy.outputs.functionAppName }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true