name: Deploy subflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: The environment to deploy to (e.g., Development, Staging, Production).
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      RESOURCE_GROUP_NAME:
        required: true
        description: The name of the Azure resource group to deploy to.


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Bicep Deployment
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: create
          name: Development
          location: eastus
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: resourceGroup
          resource-group-name: ${{ secrets.RESOURCE_GROUP_NAME }}
          template-file: ./bicep/main.bicep
          action-on-unmanage-resources: delete
          deny-settings-mode: none